---
debug: true
fallball_service_url: PUT_HERE_FALLBALL_SERVICE_URI
fallball_service_authorization_token: PUT_HERE_FALLBALL_SERVICE_AUTHORIZATION_TOKEN
oauth_key: PUT_HERE_OAUTH_KEY
oauth_secret: PUT_HERE_OAUTH_SECRET
diskspace_resource: DISKSPACE
devices_resource: DEVICES
parameters:
  ENVIRONMENT:
    0: PRODUCTION
    1: TEST
  COUNTRY:
    0: US
    1: CA
    2: UK
    3: NL
    4: IT
    5: BE
    6: SE
    7: DE
    8: FR
    9: ES
    10: CH
    11: AT
    12: AU