connector:
  restart: always
  build: .
  ports:
    - "5000:80"
  entrypoint:
    - python
    - app.py
  volumes:
    - ./connector:/connector
    - ./config.yml:/connector/config.yml
  cpu_quota: 200000
  mem_limit: 268435456