version: '2.2'
services:
  connector:
    restart: always
    build: .
    ports:
      - "5000:80"
    entrypoint:
      - python
      - app.py
    volumes:
      - ./connector:/connector
      - ./config.yml:/connector/config.yml
    cpus: 0.2
    mem_limit: 256m